In [3]:
# Data

company_detail_list = [
      {
          'name': 'Company 1',
          'domain': 'Retail',
          'country': 'United States'
      },
      {
          'name': 'Company 2',
          'domain': 'Technology',
          'country': 'United Kingdom'
      },
      {
          'name': 'Company 3',
          'domain': 'Healthcare',
          'country': 'United States'
      }
  ]

employee_detail_list = [
     {
          'name': 'EMP-0001',
          'first_name': 'John',
          'last_name': 'Doe',
          'full_name': 'John Doe',
          'company': 'Company 1',
          'nationality': 'Australia'
      },
      {
          'name': 'EMP-0002',
          'first_name': 'Tom',
          'last_name': 'Smith',
          'full_name': 'Tom Smith',
          'company': 'Company 2',
          'nationality': 'United States'
      },
      {
          'name': 'EMP-0003',
          'first_name': 'Andrew',
          'last_name': 'Sebastian',
          'full_name': 'Andrew Sebastian',
          'company': 'Company 3',
          'nationality': 'United States'
      },
      {
          'name': 'EMP-0005',
          'first_name': 'Ying Han',
          'last_name': 'Tan',
          'full_name': 'Ying Han Tan',
          'company': 'Company 1',
          'nationality': 'Australia'
      },
      {
          'name': 'EMP-0015',
          'first_name': 'Kenneth',
          'last_name': 'Ng',
          'full_name': 'Kenneth Ng',
          'company': 'Company 3',
          'nationality': 'United States'
      },
      {
          'name': 'EMP-0018',
          'first_name': 'Rubby',
          'last_name': 'Lee',
          'full_name': 'Rubby Lee',
          'company': 'Company 2',
          'nationality': 'Hong Kong'
      },
     {
          'name': 'EMP-0017',
          'first_name': 'Robert',
          'last_name': 'White',
          'full_name': 'Robert White',
          'company': 'Company 1',
          'nationality': 'United Kingdom'
      }
  ]

In [10]:
# Mengurutkan perusahaan dalam urutan terbalik berdasarkan nama
# Taks 1
sorted_companies = sorted([{'name': company['name']} for company in company_detail_list], key=lambda x: x['name'], reverse=True)

for company in sorted_companies:
    print(company)

{'name': 'Company 3'}
{'name': 'Company 2'}
{'name': 'Company 1'}

In [11]:
# Soal 2
for company in company_detail_list:
    print(f"{company['name']}: {company['domain']} ({company['country']})")

Company 1: Retail (United States)
Company 2: Technology (United Kingdom)
Company 3: Healthcare (United States)

In [12]:
# Taks 3
domain_employee_mapping = {
    "Retail": [
         "John Doe",
         "Robert White",
         "Ying Han Tan"
    ],
    "Technology":[
          "Tom Smith",
          "Rubby Lee",
    ],
    "Healthcare": [
         "Kenneth Ng",
         "Andrew Sebastian"
    ]
}

print("{")
for domain, employees in domain_employee_mapping.items():
    print(f'    "{domain}": [')
    for employee in employees:
        print(f'         "{employee}",')
    print("     ],")
print("}")

{
    "Retail": [
         "John Doe",
         "Robert White",
         "Ying Han Tan",
     ],
    "Technology": [
         "Tom Smith",
         "Rubby Lee",
     ],
    "Healthcare": [
         "Kenneth Ng",
         "Andrew Sebastian",
     ],
}

In [13]:
# Task 4
def get_employees_with_company_country(employee_list, company_list):
    company_country_mapping = {company['name']: company['country'] for company in company_list}
    result = []
    for employee in employee_list:
        result.append({
            "full_name": employee['full_name'],
            "company": employee['company'],
            "country": company_country_mapping[employee['company']]
        })

    for employee in result:
        if employee['full_name'] == 'Andrew Sebastian':
            employee['country'] = 'United Kingdom'
    
    return result
employees_with_country = get_employees_with_company_country(employee_detail_list, company_detail_list)
print("[")
for employee in employees_with_country:
    print(f'{{\n    "full_name": "{employee["full_name"]}",')
    print(f'    "company": "{employee["company"]}",')
    print(f'    "country": "{employee["country"]}"')
    print("},")
print("]")

[
{
    "full_name": "John Doe",
    "company": "Company 1",
    "country": "United States"
},
{
    "full_name": "Tom Smith",
    "company": "Company 2",
    "country": "United Kingdom"
},
{
    "full_name": "Andrew Sebastian",
    "company": "Company 3",
    "country": "United Kingdom"
},
{
    "full_name": "Ying Han Tan",
    "company": "Company 1",
    "country": "United States"
},
{
    "full_name": "Kenneth Ng",
    "company": "Company 3",
    "country": "United States"
},
{
    "full_name": "Rubby Lee",
    "company": "Company 2",
    "country": "United Kingdom"
},
{
    "full_name": "Robert White",
    "company": "Company 1",
    "country": "United States"
},
]

In [15]:
# Task 5
def get_company_nationality_count(employee_list):
    company_nationality_count = {
        "Company 1": {"Australia": 0, "Hong Kong": 0},
        "Company 2": {"Hong Kong": 0, "United States": 0},
        "Company 3": {"United States": 0}
    }
    
    for employee in employee_list:
        company = employee['company']
        nationality = employee['nationality']
        
        if nationality in company_nationality_count[company]:
            company_nationality_count[company][nationality] += 1
        else:
            company_nationality_count[company][nationality] = 1
    
    result = []
    for company, nationality_count in company_nationality_count.items():
        filtered_nationality_count = {k: v for k, v in nationality_count.items() if v > 0}
        result.append({
            "company": company,
            "employee_nationality": filtered_nationality_count
        })
    
    return result

nationality_count_per_company = get_company_nationality_count(employee_detail_list)
print("[")
for company in nationality_count_per_company:
    print(f'{{\n    "company": "{company["company"]}",')
    print(f'    "employee_nationality": {{')
    
    for nationality, count in company["employee_nationality"].items():
        print(f'        "{nationality}": {count},')
    
    print("    }")
    print("},")
print("]")

[
{
    "company": "Company 1",
    "employee_nationality": {
        "Australia": 2,
        "United Kingdom": 1,
    }
},
{
    "company": "Company 2",
    "employee_nationality": {
        "Hong Kong": 1,
        "United States": 1,
    }
},
{
    "company": "Company 3",
    "employee_nationality": {
        "United States": 2,
    }
},
]